spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/learningdb
    username: learning_user
    password: learning_password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080
